# Generated by Django 3.0.8 on 2020-08-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('by', models.CharField(blank=True, default='', max_length=200)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(blank=True, default='')),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('summaryImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('pageOneTitle', models.TextField(blank=True, default='')),
                ('pageOneImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('pageOne', models.TextField(blank=True, default='')),
                ('pageTwoTitle', models.TextField(blank=True, default='')),
                ('pageTwoImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('pageTwo', models.TextField(blank=True, default='')),
                ('pageThreeTitle', models.TextField(blank=True, default='')),
                ('pageThreeImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('pageThree', models.TextField(blank=True, default='')),
                ('pageFourTitle', models.TextField(blank=True, default='')),
                ('pageFourImage', models.ImageField(blank=True, default='', upload_to='blog/images/')),
                ('pageFour', models.TextField(blank=True, default='')),
            ],
        ),
    ]
