# Generated by Django 3.0.8 on 2020-08-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xworldblog', '0002_auto_20200827_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pageFourTitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageOneTitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageThreeTitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pageTwoTitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
