# Generated by Django 3.0.8 on 2020-09-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xworldblog', '0003_auto_20200827_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageFour',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageFourImage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageFourTitle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageThree',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageThreeImage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageThreeTitle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageTwo',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageTwoImage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='pageTwoTitle',
        ),
    ]
